### ISSUE TITLE
in host mode, it should not depend on SGX libraries when building. 

### ISSUE THREAD

**Issue by YangLiang3** [inclavare-containers/inclavare-containers#1496]

**Comment by jiazhang0** [comment]
In host mode, sgx-ecdsa verifier instance should be:
1) if sgx sdk (include dcap) is available, it should be built by default.
2) otherwise, it should not be built, and print a warning message.

In other word, I hope to see our cmake build infrastructure is going to be more smart to check the build environment dynamically instead of always depending on the manual explicitly specifying something to work.
